### ISSUE TITLE
docker with helipad

### ISSUE THREAD

**Issue by hyusetiawan** [charwick/helipad#1]
I want to start by saying how well thought out this framework in terms of productivity! I am having trouble getting up and running though and my issue might not be related to helipad per see. I use docker environment for my dev setup so I am not able to follow the typical examples that are listed here, do you have examples I can follow to render say via a webserver but using the same API?

**Comment by charwick** [comment]
Thanks! I'm afraid Docker support looks like a pretty major undertaking (if I'm understanding it correctly, I'd need to redo the frontend in HTML), and I'm not even sure live Matplotlib output is possible. Jupyter does something similar running a local webserver though, and generates its own HTML; I might suggest that as an alternative.

Helipad shouldn't be very picky about your environment, if that's why you're using Docker, but of course I'm happy to fix any problems you do run into.

**Comment by hyusetiawan** [comment]
@charwick  that's fair, thanks for the reply!
